# Generated by Django 5.0 on 2024-01-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='proc_price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
