# Generated by Django 5.0 on 2024-02-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rollno',
            new_name='roll_no',
        ),
    ]
