# Generated by Django 5.0 on 2024-02-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchno', models.CharField(max_length=30, unique=True)),
                ('time', models.CharField(max_length=20)),
                ('module', models.CharField(max_length=20)),
                ('labno', models.IntegerField()),
            ],
        ),
    ]
